module.exports = {
    code_0:{err_code:0,err_msg:"操作成功"},
    code_1:{err_code:1,err_msg:"缺少必要参数"},
    code_2:{err_code:2,err_msg:"用户名不能为空"},
    code_3:{err_code:3,err_msg:"密码不能为空"},
    code_4:{err_code:4,err_msg:"文章标题不能为空"},
    code_5:{err_code:5,err_msg:"文章内容不能为空"},
    code_6:{err_code:6,err_msg:"每页大小必须是正整数"},
    code_7:{err_code:7,err_msg:"页数必须是正整数"},
    code_8:{err_code:8,err_msg:"文章ID必须是正数"},
	code_9:{err_code:9,err_msg:"未登录或者登录已过期"},
	code_10:{err_code:10,err_msg:"用户名被占用"},
	code_11:{err_code:11,err_msg:"该文章不存在"},
	code_12:{err_code:12,err_msg:"该用户不存在"},
};
